-- =============================================================
-- 多聊天室群聊系统 初始化脚本 (PostgreSQL 14+)
-- =============================================================
-- 1. 创建库
CREATE DATABASE chat
WITH ENCODING = 'UTF8'
LC_COLLATE = 'utf8_general_ci'
LC_CTYPE = 'utf8_general_ci'
TEMPLATE template0;

-- 2. 切换到chat库（仅psql工具可用，标准SQL不支持）
\c chat;
-- 用户表
CREATE TABLE IF NOT EXISTS users (
                                     id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    nickname      VARCHAR(50),
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE
    );
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_username ON users (username) WHERE deleted = FALSE;

-- 聊天室表
CREATE TABLE IF NOT EXISTS chat_rooms (
                                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    max_users   INT          NOT NULL DEFAULT 500,
    join_policy VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    owner_id    BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE
    );
CREATE INDEX IF NOT EXISTS idx_rooms_status ON chat_rooms (status) WHERE deleted = FALSE;

-- 消息表
CREATE TABLE IF NOT EXISTS messages (
                                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        room_id      BIGINT       NOT NULL,
                                        sender_id    BIGINT       NOT NULL,
                                        content      TEXT         NOT NULL,
                                        type         VARCHAR(20)  NOT NULL DEFAULT 'CHAT',
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING_REVIEW',
    submitted_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    reviewed_at  TIMESTAMPTZ,
    reviewer_id  BIGINT,
    version      INT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE
    );
CREATE INDEX IF NOT EXISTS idx_messages_room_status_time ON messages (room_id, status, submitted_at);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_status_time ON messages (status, submitted_at);

-- 审核日志表
CREATE TABLE IF NOT EXISTS audit_logs (
                                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          message_id  BIGINT       NOT NULL,
                                          reviewer_id BIGINT,
                                          action      VARCHAR(20)  NOT NULL,
    reason      VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE
    );
CREATE INDEX IF NOT EXISTS idx_audit_message ON audit_logs (message_id);

-- 用户-聊天室关联表
CREATE TABLE IF NOT EXISTS user_chat_rooms (
                                               id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               user_id       BIGINT       NOT NULL,
                                               room_id       BIGINT       NOT NULL,
                                               member_status VARCHAR(20)  NOT NULL DEFAULT 'JOINED',
    role_in_room  VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',
    joined_at     TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE
    );
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_room ON user_chat_rooms (user_id, room_id);

-- 说明：系统管理员账号（admin / admin123）由应用启动时的 AdminInitializer 使用
-- 真实 PasswordEncoder 加密后写入，避免脚本硬编码哈希不一致，见 com.jin.chat.config.AdminInitializer

-- =============================================================
-- 全局配置表 (PostgreSQL 14+)
-- 将分散在 application.yml 的业务参数收敛到 DB，便于运行期动态调整与功能扩展
-- =============================================================
CREATE TABLE IF NOT EXISTS system_config (
                                             id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             config_key   VARCHAR(100)  NOT NULL,
    config_value VARCHAR(1000),
    config_group VARCHAR(50)   NOT NULL DEFAULT 'GENERAL',
    description  VARCHAR(255),
    editable     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted      BOOLEAN       NOT NULL DEFAULT FALSE
    );
CREATE UNIQUE INDEX IF NOT EXISTS uk_config_key ON system_config (config_key) WHERE deleted = FALSE;

-- 初始化默认配置项（示例，可在「全局配置」菜单中维护）
INSERT INTO system_config (config_key, config_value, config_group, description) VALUES
                                                                                    ('audit.max-wait-seconds', '30', 'AUDIT', '消息审核最大等待时间（秒），超时自动拒绝'),
                                                                                    ('audit.scan-interval-ms', '5000', 'AUDIT', '审核超时扫描任务执行间隔（毫秒）'),
                                                                                    ('message.max-length', '1000', 'MESSAGE', '单条消息最大字符数'),
                                                                                    ('room.default-max-users', '500', 'ROOM', '新建聊天室默认最大人数'),
                                                                                    ('push.retry-times', '1', 'PUSH', '消息推送失败重试次数')
    ON CONFLICT DO NOTHING;

-- =============================================================
-- RBAC 权限模型 (PostgreSQL 14+)
-- 用户 - 角色（多对多）、角色 - 菜单（多对多）
-- =============================================================

-- 角色表
CREATE TABLE IF NOT EXISTS roles (
                                     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     role_code   VARCHAR(50)  NOT NULL,
    role_name   VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    built_in    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE
    );
CREATE UNIQUE INDEX IF NOT EXISTS uk_role_code ON roles (role_code) WHERE deleted = FALSE;

-- 菜单表（parent_id=0 表示顶级；menu_type: DIR 目录 / MENU 菜单）
CREATE TABLE IF NOT EXISTS menus (
                                     id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     parent_id  BIGINT       NOT NULL DEFAULT 0,
                                     menu_key   VARCHAR(100) NOT NULL,
    name       VARCHAR(50)  NOT NULL,
    path       VARCHAR(200),
    sort       INT          NOT NULL DEFAULT 0,
    menu_type  VARCHAR(20)  NOT NULL DEFAULT 'MENU',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE
    );
CREATE UNIQUE INDEX IF NOT EXISTS uk_menu_key ON menus (menu_key) WHERE deleted = FALSE;

-- 用户-角色关联
CREATE TABLE IF NOT EXISTS user_roles (
                                          id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          user_id    BIGINT      NOT NULL,
                                          role_id    BIGINT      NOT NULL,
                                          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted    BOOLEAN     NOT NULL DEFAULT FALSE
    );
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_role ON user_roles (user_id, role_id);

-- 角色-菜单关联
CREATE TABLE IF NOT EXISTS role_menus (
                                          id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          role_id    BIGINT      NOT NULL,
                                          menu_id    BIGINT      NOT NULL,
                                          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted    BOOLEAN     NOT NULL DEFAULT FALSE
    );
CREATE UNIQUE INDEX IF NOT EXISTS uk_role_menu ON role_menus (role_id, menu_id);

-- 默认角色
INSERT INTO roles (role_code, role_name, description, built_in) VALUES
                                                                    ('SYS_ADMIN', '系统管理员', '拥有全部菜单权限', TRUE),
                                                                    ('ROOM_ADMIN', '聊天室管理员', '管理聊天室与消息审核等业务', TRUE),
                                                                    ('USER', '普通用户', '基础聊天功能', TRUE)
    ON CONFLICT DO NOTHING;

-- 顶级菜单
INSERT INTO menus (parent_id, menu_key, name, path, sort, menu_type) VALUES
                                                                         (0, 'rooms', '聊天室列表', '/app/rooms', 1, 'MENU'),
                                                                         (0, 'my-messages', '我的消息', '/app/my-messages', 2, 'MENU'),
                                                                         (0, 'broadcast', '消息广播', '/app/broadcast', 3, 'MENU'),
                                                                         (0, 'audit', '消息审核', '/app/audit', 4, 'MENU'),
                                                                         (0, 'metrics', '性能监控', '/app/metrics', 5, 'MENU'),
                                                                         (0, 'configs', '全局配置', '/app/configs', 6, 'MENU'),
                                                                         (0, 'system', '系统管理', NULL, 7, 'DIR')
    ON CONFLICT DO NOTHING;

-- 系统管理子菜单
INSERT INTO menus (parent_id, menu_key, name, path, sort, menu_type)
SELECT (SELECT id FROM menus WHERE menu_key = 'system'), 'system:users', '用户管理', '/app/system/users', 1, 'MENU'
    ON CONFLICT DO NOTHING;
INSERT INTO menus (parent_id, menu_key, name, path, sort, menu_type)
SELECT (SELECT id FROM menus WHERE menu_key = 'system'), 'system:roles', '角色管理', '/app/system/roles', 2, 'MENU'
    ON CONFLICT DO NOTHING;

-- 角色-菜单授权
-- 系统管理员：全部菜单
INSERT INTO role_menus (role_id, menu_id)
SELECT (SELECT id FROM roles WHERE role_code = 'SYS_ADMIN'), m.id
FROM menus m
    ON CONFLICT DO NOTHING;
-- 聊天室管理员：业务菜单
INSERT INTO role_menus (role_id, menu_id)
SELECT (SELECT id FROM roles WHERE role_code = 'ROOM_ADMIN'), m.id
FROM menus m
WHERE m.menu_key IN ('rooms', 'my-messages', 'broadcast', 'audit')
    ON CONFLICT DO NOTHING;
-- 普通用户：基础菜单
INSERT INTO role_menus (role_id, menu_id)
SELECT (SELECT id FROM roles WHERE role_code = 'USER'), m.id
FROM menus m
WHERE m.menu_key IN ('rooms', 'my-messages')
    ON CONFLICT DO NOTHING;

-- =============================================================
-- 将登录令牌有效期收敛到全局配置（PostgreSQL）
-- 默认 120 分钟（2 小时）
-- =============================================================
INSERT INTO system_config (config_key, config_value, config_group, description) VALUES
    ('jwt.expire-minutes', '120', 'AUTH', '登录令牌有效期（分钟），默认2小时')
    ON CONFLICT DO NOTHING;

-- =============================================================
-- 新增「工作台」概览菜单（PostgreSQL），作为登录后的默认落地页
-- =============================================================
INSERT INTO menus (parent_id, menu_key, name, path, sort, menu_type) VALUES
    (0, 'dashboard', '工作台', '/app/dashboard', 0, 'MENU')
    ON CONFLICT DO NOTHING;

-- 工作台对所有角色可见
INSERT INTO role_menus (role_id, menu_id)
SELECT r.id, m.id
FROM roles r CROSS JOIN menus m
WHERE m.menu_key = 'dashboard'
    ON CONFLICT DO NOTHING;


