-- =============================================================
-- 多聊天室群聊系统 初始化脚本 (PostgreSQL 14+)
-- =============================================================

-- 用户表
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    nickname      VARCHAR(50),
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_username ON users (username) WHERE deleted = FALSE;

-- 聊天室表
CREATE TABLE IF NOT EXISTS chat_rooms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    max_users   INT          NOT NULL DEFAULT 500,
    join_policy VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    owner_id    BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_rooms_status ON chat_rooms (status) WHERE deleted = FALSE;

-- 消息表
CREATE TABLE IF NOT EXISTS messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      BIGINT       NOT NULL,
    sender_id    BIGINT       NOT NULL,
    content      TEXT         NOT NULL,
    type         VARCHAR(20)  NOT NULL DEFAULT 'CHAT',
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING_REVIEW',
    submitted_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    reviewed_at  TIMESTAMPTZ,
    reviewer_id  BIGINT,
    version      INT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_messages_room_status_time ON messages (room_id, status, submitted_at);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_status_time ON messages (status, submitted_at);

-- 审核日志表
CREATE TABLE IF NOT EXISTS audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT       NOT NULL,
    reviewer_id BIGINT,
    action      VARCHAR(20)  NOT NULL,
    reason      VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_audit_message ON audit_logs (message_id);

-- 用户-聊天室关联表
CREATE TABLE IF NOT EXISTS user_chat_rooms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    room_id       BIGINT       NOT NULL,
    member_status VARCHAR(20)  NOT NULL DEFAULT 'JOINED',
    role_in_room  VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',
    joined_at     TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_room ON user_chat_rooms (user_id, room_id);

-- 说明：系统管理员账号（admin / admin123）由应用启动时的 AdminInitializer 使用
-- 真实 PasswordEncoder 加密后写入，避免脚本硬编码哈希不一致，见 com.jin.chat.config.AdminInitializer
