-- =============================================================
-- RBAC 权限模型 (PostgreSQL 14+)
-- 用户 - 角色（多对多）、角色 - 菜单（多对多）
-- =============================================================

-- 角色表
CREATE TABLE IF NOT EXISTS roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code   VARCHAR(50)  NOT NULL,
    role_name   VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    built_in    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_role_code ON roles (role_code) WHERE deleted = FALSE;

-- 菜单表（parent_id=0 表示顶级；menu_type: DIR 目录 / MENU 菜单）
CREATE TABLE IF NOT EXISTS menus (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  BIGINT       NOT NULL DEFAULT 0,
    menu_key   VARCHAR(100) NOT NULL,
    name       VARCHAR(50)  NOT NULL,
    path       VARCHAR(200),
    sort       INT          NOT NULL DEFAULT 0,
    menu_type  VARCHAR(20)  NOT NULL DEFAULT 'MENU',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_menu_key ON menus (menu_key) WHERE deleted = FALSE;

-- 用户-角色关联
CREATE TABLE IF NOT EXISTS user_roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    role_id    BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted    BOOLEAN     NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_role ON user_roles (user_id, role_id);

-- 角色-菜单关联
CREATE TABLE IF NOT EXISTS role_menus (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    BIGINT      NOT NULL,
    menu_id    BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted    BOOLEAN     NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_role_menu ON role_menus (role_id, menu_id);

-- 默认角色
INSERT INTO roles (role_code, role_name, description, built_in) VALUES
    ('SYS_ADMIN', '系统管理员', '拥有全部菜单权限', TRUE),
    ('ROOM_ADMIN', '聊天室管理员', '管理聊天室与消息审核等业务', TRUE),
    ('USER', '普通用户', '基础聊天功能', TRUE)
    ON CONFLICT DO NOTHING;

-- 顶级菜单
INSERT INTO menus (parent_id, menu_key, name, path, sort, menu_type) VALUES
    (0, 'rooms', '聊天室列表', '/app/rooms', 1, 'MENU'),
    (0, 'my-messages', '我的消息', '/app/my-messages', 2, 'MENU'),
    (0, 'broadcast', '消息广播', '/app/broadcast', 3, 'MENU'),
    (0, 'audit', '消息审核', '/app/audit', 4, 'MENU'),
    (0, 'metrics', '性能监控', '/app/metrics', 5, 'MENU'),
    (0, 'configs', '全局配置', '/app/configs', 6, 'MENU'),
    (0, 'system', '系统管理', NULL, 7, 'DIR')
    ON CONFLICT DO NOTHING;

-- 系统管理子菜单
INSERT INTO menus (parent_id, menu_key, name, path, sort, menu_type)
SELECT (SELECT id FROM menus WHERE menu_key = 'system'), 'system:users', '用户管理', '/app/system/users', 1, 'MENU'
    ON CONFLICT DO NOTHING;
INSERT INTO menus (parent_id, menu_key, name, path, sort, menu_type)
SELECT (SELECT id FROM menus WHERE menu_key = 'system'), 'system:roles', '角色管理', '/app/system/roles', 2, 'MENU'
    ON CONFLICT DO NOTHING;
INSERT INTO menus (parent_id, menu_key, name, path, sort, menu_type)
SELECT (SELECT id FROM menus WHERE menu_key = 'system'), 'system:menus', '菜单权限管理', '/app/system/menus', 3, 'MENU'
    ON CONFLICT DO NOTHING;

-- 角色-菜单授权
-- 系统管理员：全部菜单
INSERT INTO role_menus (role_id, menu_id)
SELECT (SELECT id FROM roles WHERE role_code = 'SYS_ADMIN'), m.id
FROM menus m
    ON CONFLICT DO NOTHING;
-- 聊天室管理员：业务菜单
INSERT INTO role_menus (role_id, menu_id)
SELECT (SELECT id FROM roles WHERE role_code = 'ROOM_ADMIN'), m.id
FROM menus m
WHERE m.menu_key IN ('rooms', 'my-messages', 'broadcast', 'audit')
    ON CONFLICT DO NOTHING;
-- 普通用户：基础菜单
INSERT INTO role_menus (role_id, menu_id)
SELECT (SELECT id FROM roles WHERE role_code = 'USER'), m.id
FROM menus m
WHERE m.menu_key IN ('rooms', 'my-messages')
    ON CONFLICT DO NOTHING;
